apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "helper.fullname" . }}
  labels:
    app: {{ template "helper.name" . }}
    chart: {{ template "helper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        app: {{ template "helper.name" . }}
        release: {{ .Release.Name }}
    spec:
      template:
        spec:
          serviceAccountName: certs
          containers:
          - name: {{ template "helper.fullname" . }}
            image: {{ template "helper.image" . }}
            imagePullPolicy: Always
            {{- if .Values.env }}
            env:
            {{- with .Values.env }}
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- end }}
          restartPolicy: Never
          backoffLimit: {{ .Values.backoffLimit }}
          activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
          ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
          concurrencyPolicy: Forbid